# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_auto_20161110_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 11, 43, 29, 928000, tzinfo=utc)),
        ),
    ]
